config/routes.rb
Tracker::Application.routes.draw do
  get 'sign_in' => 'sessions#new'
  delete 'sign_out' => 'sessions#destroy'

  resource :sessions, only: :create

  resource :register, only: [ :new, :create ]
  resources :users
  resources :trainees, only: :index

  scope 'utilities' do
    resources :departments, except: [ :show, :edit, :new ]
    resources :job_titles, except: [ :show, :edit, :new ]
    resources :categories, except: [ :show, :edit, :new ]
  end

  namespace :api do
    namespace :v1 do
      resources :trainees, only: [ :create, :update, :destroy ]
      post 'trainees/search' => 'trainees#search'
    end
  end

  root 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  include AsLogicalDelete

  belongs_to :company

  validates_presence_of :category_name
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :departments
  has_many :job_titles
  has_many :categories
  has_many :trainees, -> { where(deleted: false) }
end

app/models/concerns/as_logical_delete.rb
module AsLogicalDelete
  extend ActiveSupport::Concern

  included do
    scope :active, -> { where(deleted: false) }

    before_validation(on: :create) { :activate }

    def activate
      self.deleted = false
    end

    def deactivate
      update_attribute(:deleted, true)
    end
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  include AsLogicalDelete

  belongs_to :company

  validates_presence_of :department_name
end

app/models/job_title.rb
class JobTitle < ActiveRecord::Base
  include AsLogicalDelete

  belongs_to :company

  validates_presence_of :job_title_name
end

app/models/nil_user.rb
class NilUser
  def self.company_id; -1; end
end

app/models/trainee.rb
class Trainee < ActiveRecord::Base
  include AsLogicalDelete

  belongs_to :company
  belongs_to :department
  belongs_to :category
  belongs_to :job_title

  validates_presence_of :first_name, :last_name

  delegate :department_name, to: :department, allow_nil: true
  delegate :category_name, to: :category, allow_nil: true
  delegate :job_title_name, to: :job_title, allow_nil: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authem::User

  belongs_to :company

  validates_presence_of :first_name, :last_name
  validates_uniqueness_of :email

  accepts_nested_attributes_for :company

  delegate :company_name, to: :company, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Authem::ControllerSupport

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  def success_action
    action_name == "create" ? :added : :updated
  end

  def current_company
    current_user ? current_user.company : nil
  end

  hide_action(:success_action)
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  expose(:company) { current_user.company }
  expose(:categories) { Category.active.where(company_id: company.id) }
  expose(:category, attributes: :category_params)

  def create
    category.save ?
      flash[:success] = ["You successfully", success_action, category.category_name].join(" ") :
      flash[:alert] = "Category name can't be blank"

    redirect_to categories_path
  end
  alias update create

  def destroy
    category.deactivate
    flash[:success] = "You successfully deleted #{category.category_name}"
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit!
  end

end

app/controllers/concerns/as_company_meta_data_controller.rb
module AsCompanyMetaDataController
  extend ActiveSupport::Concern

  included do
    expose(:company) { current_company }
    expose(:departments) { departments_for(company) }
    expose(:categories) { categories_for(company) }
    expose(:job_titles) { job_titles_for(company) }

    private

    def map_collection_for(collection, name)
      collection.map do |d|
        [d.send(name), d.id]
      end
    end

    def departments_for(company)
      map_collection_for(company.departments.active, :department_name)
    end

    def job_titles_for(company)
      map_collection_for(company.job_titles.active, :job_title_name)
    end

    def categories_for(company)
      map_collection_for(company.categories.active, :category_name)
    end
  end
end

app/controllers/concerns/as_users_controller.rb
module AsUsersController
  extend ActiveSupport::Concern

  included do
    expose(:company) { Company.find_or_create_by(company_params) }
    expose(:users) { User.where(company_id: company_id) }
    expose(:user, attributes: :user_params)

    private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def company_params
      params.require(:user).permit(:company_name)
    end

    def company_id
      (current_user || NilUser).company_id
    end
  end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  expose(:company) { current_user.company }
  expose(:departments) { Department.active.where(company_id: company.id) }
  expose(:department, attributes: :department_params)

  def create
    department.save ?
      flash[:success] = ["You successfully", success_action, department.department_name].join(" ") :
      flash[:alert] = "Department name can't be blank"
    redirect_to departments_path
  end
  alias update create

  def destroy
    department.deactivate
    flash[:success] = "You successfully deleted #{department.department_name}"
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/job_titles_controller.rb
class JobTitlesController < ApplicationController
  expose(:company) { current_user.company }
  expose(:job_titles) { JobTitle.active.where(company_id: company.id) }
  expose(:job_title, attributes: :job_title_params)

  def create
    job_title.save ?
      flash[:success] = ["You successfully", success_action, job_title.job_title_name].join(" ") :
      flash[:alert] = "Job Title name can't be blank"

    redirect_to job_titles_path
  end
  alias update create

  def destroy
    job_title.deactivate
    flash[:success] = "You successfully deleted #{job_title.job_title_name}"
    redirect_to job_titles_path
  end

  private

  def job_title_params
    params.require(:job_title).permit!
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  respond_to :html

  include AsUsersController

  def create
    if user.update_attributes(company_id: company.id)
      flash[:success] = "Thank you for registering"
      sign_in(user)
      respond_with current_user, location: root_url
    else
      flash.now.alert = "User with that email already exists"
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'session'

  expose(:user) { User.find_by_email(params[:email]) }

  def create
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_back_or_to(:root)
    else
      flash.now.alert = "Email and password don't match. Please try again"
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to :root
  end

end

app/controllers/trainees_controller.rb
class TraineesController < ApplicationController
  include AsCompanyMetaDataController

  expose(:trainee)

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html

  expose(:company) do
    Company.find_or_create_by(company_params)
  end
  expose(:users) do
    User.where(company_id: company_id)
  end
  expose(:user, attributes: :user_params)

  def create
    if user.update_attributes(company_id: company.id)
      flash[:success] = "Thank you for registering"
      sign_in(user)
      respond_with current_user, location: root_url
    else
      flash.now.alert = "User with that email already exists"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def company_params
    params.require(:user).permit(:company_name)
  end

  def company_id
    (current_user || NilUser).company_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_home
    active_matcher URI.decode(request.fullpath) == "/"
  end

  def active_if(url)
    active_matcher URI.decode(request.fullpath).match(url)
  end

  def active_matcher(matcher)
    matcher ? "active" : ""
  end
end

app/views/layouts/application.html.haml
!!!
%html(lang="en-US")
  %head
    %title Training Tracker 7
    %meta(charset="UTF-8")
    %meta(content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" name="viewport")
    = stylesheet_link_tag "application"
    /[if IE]
      = javascript_include_tag "html5"
    = javascript_include_tag "application"
    = yield :head
    = csrf_meta_tags
  %body
    %header
      .column
        %h1= link_to "Training Tracker 7", root_path
        .session
          - if signed_in?
            %p 
              Welcome, #{current_user.first_name}
            = link_to "Sign Out", sign_out_path, class: "button", method: :delete
          - else
            = link_to "Sign In", sign_in_path
            = link_to "Register", new_register_path
        %nav
          %ul
            %li{ class: active_home }= link_to "Home", root_path
            - if signed_in?
              %li{ class: active_if("trainees") }= link_to "People", trainees_path
              - ["Tasks", "Training"].each do |nav|
                %li= link_to nav, "#"
              %li{ class: active_if("utilities") }= link_to "Utilities", departments_path
              %li{ class: active_if("users") }= link_to "Admin", users_path

    #page_head
      .column
        = yield :page_head

    = yield :flash

    #content.column
      = yield

    #modal_layer

app/views/layouts/session.html.haml
!!!
%html(lang="en-US")
  %head
    %title Training Tracker 7
    %meta(charset="UTF-8")
    %meta(content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" name="viewport")
    = stylesheet_link_tag "application"
    /[if IE]
      = javascript_include_tag "html5"
    = javascript_include_tag "application"
    = yield :head
    = csrf_meta_tags
  %body
    %header
      .column
        %h1= link_to "Training Tracker 7", root_path

    #page_head
      .column
        = yield :page_head

    = yield :flash

    #content.column_wide
      = yield

app/views/shared/_delete_modal.html.haml
#delete_modal.modal
  #confirm_delete
    %header
      %h1.title
      = link_to "Close", "#", class: "close"
    .actions
      = link_to "Yes", "#", class: "button confirm"
      = link_to "No", "#", class: "button close"

app/views/shared/_flash_message.html.haml
= content_for :flash do
  - flash.keys.each do |key|
    .flash{ class: key }
      %p= flash[key.to_sym]

app/views/shared/_user_form.html.haml
%fieldset
  %header
    %h1 Personal Information
  %dl.half
    %dt= f.label :first_name, 'First'
    %dd= f.text_field :first_name
  %dl.half
    %dt= f.label :last_name, 'Last'
    %dd= f.text_field :last_name
%fieldset
  %header
    %h1 Account Information
  %dl.half
    %dt= f.label :email, 'Email Address'
    %dd= f.email_field :email
  %dl.half.clear
    %dt= f.label :password
    %dd= f.password_field :password
  %dl.half
    %dt= f.label :password_confirmation, 'Confirm Password'
    %dd= f.password_field :password_confirmation

app/views/shared/_utilities_nav.html.haml
%h1 Utilities
%nav
  %ul
    %li{ class: active_if("departments") }= link_to "Departments", departments_path
    %li{ class: active_if("job_titles") }= link_to "Job Titles", job_titles_path
    %li{ class: active_if("categories") }= link_to "Categories", categories_path